POST http://localhost:8877/api/users/login
Content-Type: application/json

{
  "user":{
    "email": "jake@jake.jake",
    "password": "1234"
  }
}

###
POST http://localhost:8877/api/users/signup
Content-Type: application/json

{
  "user":{
    "username": "jake",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}